<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Daniel Rodríguez García y Lisseth Corella Esquivel" />


<title>Reporte de Gira Punta Morales</title>

<script src="Reporte_gira_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="Reporte_gira_files/bootstrap-3.3.5/css/sandstone.min.css" rel="stylesheet" />
<script src="Reporte_gira_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="Reporte_gira_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="Reporte_gira_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="Reporte_gira_files/navigation-1.1/tabsets.js"></script>
<link href="Reporte_gira_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="Reporte_gira_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->





<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Reporte de Gira Punta Morales</h1>
<h4 class="author"><em>Daniel Rodríguez García y Lisseth Corella Esquivel</em></h4>
<h4 class="date"><em>29 de marzo de 2019</em></h4>

</div>

<div id="TOC">
<ul>
<li><a href="#metodologia">Metodología</a></li>
<li><a href="#resultados">Resultados</a><ul>
<li><a href="#problematica-de-los-sitios-de-estudio">Problemática de los sitios de Estudio</a><ul>
<li><a href="#refugio-de-vida-silvestre-mata-redonda">Refugio de Vida Silvestre Mata Redonda</a></li>
<li><a href="#salinera-de-cocorocas">Salinera de Cocorocas</a></li>
<li><a href="#camaronera-de-chomes">Camaronera de Chomes</a></li>
</ul></li>
<li><a href="#listado-de-especies-e-historia-natural">Listado de especies e historia natural</a></li>
<li><a href="#analisis-de-diversidad">Análisis de diversidad</a><ul>
<li><a href="#diversidad-verdadera">Diversidad Verdadera</a></li>
<li><a href="#indice-de-diversidad">Índice de diversidad</a></li>
<li><a href="#indice-de-dominancia">Índice de dominancia</a></li>
<li><a href="#perfiles-de-diversidad">Perfiles de diversidad</a></li>
</ul></li>
</ul></li>
<li><a href="#discusion">Discusión</a></li>
<li><a href="#bibliografia">Bibliografía</a></li>
</ul>
</div>

<div id="metodologia" class="section level1">
<h1>Metodología</h1>
<p align="justify">
Las observaciones se realizaron en Marzo del 2019 en tres sitios del Pacífico Norte en Costa Rica. El primero fue en el Refugio de Vida Silvestre Mata Redonda, cerca del margen del río Tempisque, en el Golfo de Nicoya, Guanacaste. El segundo sitio fue en las salineras de Cocorocas, perteneciente al distrito de Chomes del cantón central de Puntarenas. El último punto fue en las camaroneras de Chomes. A cada sitio le reconocimos los problemas ambientales presentes en el momento de la visita. Los problemas evaluados fueron Residuos sólidos, Vertido de Hidrocarburos, Residuos sólidos, Aguas residuales y Tala de árboles.
</p>
<p align="justify">
La metodología para describir comportamientos de las aves consitió en observaciones directas y conteos en campo durante 3-4 horas.Tanto las observaciones del Refugio como en las camaroneras de Chomes fueron realizados en horas de la tarde, en las Salineras las observaciones se realizaron tanto en la mañana como una hora en la tarde. A cada especie se le investigó el órden, la familia, el estatus (R= Residente, M= Migratorio, A= Accidental, SC= Especie Sin Comprobante, END= Endémica y RR= Residente reproductor) y el hábito alimenticio.
</p>
<p align="justify">
Por último, se realizó un análisis de Diversidad Verdadera para observar las diferencias en la diversidad <strong>alpha, beta y gamma</strong> entre los tres sitios. La Diversidad verdadera expresa el número equivalente de especies o número de efecto de especies (Hill numbers). Se transforma las comunidades cuyas especies tienen diferentes abundancias, en comunidades con abundancias iguales. Así podemos comparar número de especies entre comunidades. Este análisis viene a solventar los problemas de duplicación que tienen los índices de diversidad tradicional como Shannon y Simpson <span class="citation">(Hoffmann and Hoffmann 2008; Moreno et al. 2011; Lou and González-Oreja 2012)</span>.
</p>
</div>
<div id="resultados" class="section level1">
<h1>Resultados</h1>
<div id="problematica-de-los-sitios-de-estudio" class="section level2">
<h2>Problemática de los sitios de Estudio</h2>
<div id="refugio-de-vida-silvestre-mata-redonda" class="section level3">
<h3>Refugio de Vida Silvestre Mata Redonda</h3>
<p align="center">
<img src="1.jpg" />
</p>
<p align="center">
<strong>Figura 1</strong>. Paisaje del Humedal dentro del Refugio de Vida Silvestre Mata Redonda, Guanacaste.
</p>
<br />
<br />

<p align="center">
<table>
<thead>
<tr class="header">
<th>RFS Mata Redonda</th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Residuos Sólidos</td>
<td>-</td>
<td>x</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Vertido de Hidrocarburos</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Basura en General</td>
<td>-</td>
<td>x</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Aguas Residuales</td>
<td>x</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Tala</td>
<td>x</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
</p>
<ol start="0" style="list-style-type: decimal">
<li>No hay evidencia presente</li>
<li>Hay una leve sospecha</li>
<li>La afectación y contenido es leve</li>
<li>La afectación es moderada en los alrededores</li>
<li>La afectación es fuerte y evidente</li>
<li>La afectación es grave (hay descontrol)</li>
</ol>
</div>
<div id="salinera-de-cocorocas" class="section level3">
<h3>Salinera de Cocorocas</h3>
<p align="center">
<img src="2.jpg" />
</p>
<p align="center">
<strong>Figura 2</strong>. Paisaje de la Salinera de Cocorocas, Chomes.
</p>
<br />
<br />

<p align="center">
<table>
<thead>
<tr class="header">
<th>Cocorocas</th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Residuos Sólidos</td>
<td>-</td>
<td>-</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Vertido de Hidrocarburos</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Basura en General</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Aguas Residuales</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Tala</td>
<td>-</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
</p>
<ol start="0" style="list-style-type: decimal">
<li>No hay evidencia presente</li>
<li>Hay una leve sospecha</li>
<li>La afectación y contenido es leve</li>
<li>La afectación es moderada en los alrededores</li>
<li>La afectación es fuerte y evidente</li>
<li>La afectación es grave (hay descontrol)</li>
</ol>
</div>
<div id="camaronera-de-chomes" class="section level3">
<h3>Camaronera de Chomes</h3>
<p align="center">
<img src="5.jpg" />
</p>
<p align="center">
<strong>Figura 3</strong>. Paisaje de la Camaronera de Chomes, Puntarenas.
</p>
<br />
<br />

<p align="center">
<table>
<thead>
<tr class="header">
<th>Chomes</th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Residuos Sólidos</td>
<td>-</td>
<td>-</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Vertido de Hidrocarburos</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Basura en General</td>
<td>-</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Aguas Residuales</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Tala</td>
<td>-</td>
<td>X</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
</p>
<ol start="0" style="list-style-type: decimal">
<li>No hay evidencia presente</li>
<li>Hay una leve sospecha</li>
<li>La afectación y contenido es leve</li>
<li>La afectación es moderada en los alrededores</li>
<li>La afectación es fuerte y evidente</li>
<li>La afectación es grave (hay descontrol)</li>
</ol>
</div>
</div>
<div id="listado-de-especies-e-historia-natural" class="section level2">
<h2>Listado de especies e historia natural</h2>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left">Especie</th>
<th align="left">Orden</th>
<th align="left">Familia</th>
<th align="left">Estatus</th>
<th align="left">Alimentacion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Columbina inca</td>
<td align="left">Columbiformes</td>
<td align="left">Columbidae</td>
<td align="left">R</td>
<td align="left">Semillas</td>
</tr>
<tr class="even">
<td align="left">Columbina passerina</td>
<td align="left">Columbiformes</td>
<td align="left">Columbidae</td>
<td align="left">R</td>
<td align="left">Semillas</td>
</tr>
<tr class="odd">
<td align="left">Leptotila verreauxi</td>
<td align="left">Columbiformes</td>
<td align="left">Columbidae</td>
<td align="left">R</td>
<td align="left">Semillas</td>
</tr>
<tr class="even">
<td align="left">Zenaida asiatica</td>
<td align="left">Columbiformes</td>
<td align="left">Columbidae</td>
<td align="left">R.M</td>
<td align="left">Semillas</td>
</tr>
<tr class="odd">
<td align="left">Crotophaga sulcirostris</td>
<td align="left">Cuculiformes</td>
<td align="left">Cuculidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Jacana spinosa</td>
<td align="left">Charadriiformes</td>
<td align="left">Jacanidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="odd">
<td align="left">Jabiru mycteria</td>
<td align="left">Ciconiiformes</td>
<td align="left">Ciconiidae</td>
<td align="left">R</td>
<td align="left">Anguilas</td>
</tr>
<tr class="even">
<td align="left">Mycteria americana</td>
<td align="left">Ciconiiformes</td>
<td align="left">Ciconiidae</td>
<td align="left">R.M</td>
<td align="left">Peces</td>
</tr>
<tr class="odd">
<td align="left">Trigisoma mexicanum</td>
<td align="left">Pelecaniformes</td>
<td align="left">Ardeidae</td>
<td align="left">R</td>
<td align="left">Peces</td>
</tr>
<tr class="even">
<td align="left">Ardea herodias</td>
<td align="left">Pelecaniformes</td>
<td align="left">Ardeidae</td>
<td align="left">M</td>
<td align="left">Peces</td>
</tr>
<tr class="odd">
<td align="left">Ardea alba</td>
<td align="left">Pelecaniformes</td>
<td align="left">Ardeidae</td>
<td align="left">R.M</td>
<td align="left">Peces</td>
</tr>
<tr class="even">
<td align="left">Bubulcus ibis</td>
<td align="left">Pelecaniformes</td>
<td align="left">Ardeidae</td>
<td align="left">R.M</td>
<td align="left">Insectos</td>
</tr>
<tr class="odd">
<td align="left">Coragyps atratus</td>
<td align="left">Cathartiformes</td>
<td align="left">Cathartidae</td>
<td align="left">R</td>
<td align="left">Frutas</td>
</tr>
<tr class="even">
<td align="left">Cathartes aura</td>
<td align="left">Cathartiformes</td>
<td align="left">Cathartidae</td>
<td align="left">R.M</td>
<td align="left">carroña</td>
</tr>
<tr class="odd">
<td align="left">Parabuteo unicintus</td>
<td align="left">Accipitriformes</td>
<td align="left">Accipitridae</td>
<td align="left">R.M</td>
<td align="left">Vertebrados</td>
</tr>
<tr class="even">
<td align="left">Eumomota superciliosa</td>
<td align="left">Coraciiformes</td>
<td align="left">Momotidae</td>
<td align="left">R</td>
<td align="left">Inectos</td>
</tr>
<tr class="odd">
<td align="left">Melanerpes hofmannii</td>
<td align="left">Piciformes</td>
<td align="left">Picidae</td>
<td align="left">R-END</td>
<td align="left">Frutas</td>
</tr>
<tr class="even">
<td align="left">Caracara cheriway</td>
<td align="left">Falconiformes</td>
<td align="left">Falconidae</td>
<td align="left">R</td>
<td align="left">Vertebrados</td>
</tr>
<tr class="odd">
<td align="left">Herpetotheres cachinnans</td>
<td align="left">Falconiformes</td>
<td align="left">Falconidae</td>
<td align="left">R</td>
<td align="left">Vertebrados</td>
</tr>
<tr class="even">
<td align="left">Amazona albifrons</td>
<td align="left">Psittaciformes</td>
<td align="left">Psittacidae</td>
<td align="left">R</td>
<td align="left">Semillas</td>
</tr>
<tr class="odd">
<td align="left">Sublegatus arenarum</td>
<td align="left">Oxyruncidae</td>
<td align="left">Onychorhynchidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Myiarchus crinitus</td>
<td align="left">Passeriformes</td>
<td align="left">Tyrannidae</td>
<td align="left">M</td>
<td align="left">Insectos</td>
</tr>
<tr class="odd">
<td align="left">Tyrannus melancholicus</td>
<td align="left">Passeriformes</td>
<td align="left">Tyrannidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Calocitta formosa</td>
<td align="left">Passeriformes</td>
<td align="left">Corvidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="odd">
<td align="left">Hirundo rustica</td>
<td align="left">Passeriformes</td>
<td align="left">Hirundinidae</td>
<td align="left">M</td>
<td align="left">Vegetación</td>
</tr>
<tr class="even">
<td align="left">Campylorhynchus rufinucha</td>
<td align="left">Passeriformes</td>
<td align="left">Troglodytidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="odd">
<td align="left">Quiscalus mexicanus</td>
<td align="left">Passeriformes</td>
<td align="left">Icteridae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Patagioenas flavirostris</td>
<td align="left">Columbiformes</td>
<td align="left">Columbidae</td>
<td align="left">R</td>
<td align="left">Semillas</td>
</tr>
<tr class="odd">
<td align="left">Himantopus mexicanus</td>
<td align="left">Charadriiformes</td>
<td align="left">Recurvirostridae</td>
<td align="left">R.M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="even">
<td align="left">Pluvialis squatarola</td>
<td align="left">Charadriiformes</td>
<td align="left">Charadriidae</td>
<td align="left">M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="odd">
<td align="left">Charadrius wilsonia</td>
<td align="left">Charadriiformes</td>
<td align="left">Charadriidae</td>
<td align="left">R.M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="even">
<td align="left">Charadrius semipalmatus</td>
<td align="left">Charadriiformes</td>
<td align="left">Charadriidae</td>
<td align="left">M</td>
<td align="left">Moluscos</td>
</tr>
<tr class="odd">
<td align="left">Numenius phaeopus</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="even">
<td align="left">Limosa fedoa</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Vegetación</td>
</tr>
<tr class="odd">
<td align="left">Arenaria interpes</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Moluscos</td>
</tr>
<tr class="even">
<td align="left">Calidris minutilla</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Moluscos</td>
</tr>
<tr class="odd">
<td align="left">Calidris mauri</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Moluscos</td>
</tr>
<tr class="even">
<td align="left">Limnodromus griseus</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Moluscos</td>
</tr>
<tr class="odd">
<td align="left">Actitis macularius</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Tringa semipalmata</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="odd">
<td align="left">Leucophaeus atricilla</td>
<td align="left">Charadriiformes</td>
<td align="left">Laridae</td>
<td align="left">M</td>
<td align="left">Peces</td>
</tr>
<tr class="even">
<td align="left">Gelochelidon nilotica</td>
<td align="left">Charadriiformes</td>
<td align="left">Laridae</td>
<td align="left">M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="odd">
<td align="left">Thalasseus maximus</td>
<td align="left">Charadriiformes</td>
<td align="left">Laridae</td>
<td align="left">M</td>
<td align="left">Peces</td>
</tr>
<tr class="even">
<td align="left">Thalasseus sandvicensis</td>
<td align="left">Charadriiformes</td>
<td align="left">Laridae</td>
<td align="left">M</td>
<td align="left">Peces</td>
</tr>
<tr class="odd">
<td align="left">Rynchops niger</td>
<td align="left">Charadriiformes</td>
<td align="left">Laridae</td>
<td align="left">M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="even">
<td align="left">Fregata magnificens</td>
<td align="left">Suliformes</td>
<td align="left">Fregatidae</td>
<td align="left">R</td>
<td align="left">Peces</td>
</tr>
<tr class="odd">
<td align="left">Egretta thula</td>
<td align="left">Pelecaniformes</td>
<td align="left">Ardeidae</td>
<td align="left">R.M</td>
<td align="left">Peces</td>
</tr>
<tr class="even">
<td align="left">Egretta caerulea</td>
<td align="left">Pelecaniformes</td>
<td align="left">Ardeidae</td>
<td align="left">R.M</td>
<td align="left">Peces</td>
</tr>
<tr class="odd">
<td align="left">Egretta tricolor</td>
<td align="left">Pelecaniformes</td>
<td align="left">Ardeidae</td>
<td align="left">R.M</td>
<td align="left">Peces</td>
</tr>
<tr class="even">
<td align="left">Butorides virescens</td>
<td align="left">Pelecaniformes</td>
<td align="left">Ardeidae</td>
<td align="left">R.M</td>
<td align="left">Peces</td>
</tr>
<tr class="odd">
<td align="left">Nycticorax nycticorax</td>
<td align="left">Pelecaniformes</td>
<td align="left">Ardeidae</td>
<td align="left">R.M</td>
<td align="left">Vertebrados</td>
</tr>
<tr class="even">
<td align="left">Eudocimus albus</td>
<td align="left">Pelecaniformes</td>
<td align="left">Threskiornithidae</td>
<td align="left">R</td>
<td align="left">Moluscos</td>
</tr>
<tr class="odd">
<td align="left">Platalea ajaja</td>
<td align="left">Pelecaniformes</td>
<td align="left">Threskiornithidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Pandion haliaetus</td>
<td align="left">Accipitriformes</td>
<td align="left">Pandionidae</td>
<td align="left">M</td>
<td align="left">Vertebrados</td>
</tr>
<tr class="odd">
<td align="left">Buteogallus anthracinus</td>
<td align="left">Accipitriformes</td>
<td align="left">Accipitridae</td>
<td align="left">R</td>
<td align="left">Reptiles</td>
</tr>
<tr class="even">
<td align="left">Buteo plagiatus</td>
<td align="left">Accipitriformes</td>
<td align="left">Accipitridae</td>
<td align="left">R</td>
<td align="left">Vertebrados</td>
</tr>
<tr class="odd">
<td align="left">Buteo albonotatus</td>
<td align="left">Accipitriformes</td>
<td align="left">Accipitridae</td>
<td align="left">R.M</td>
<td align="left">Vertebrados</td>
</tr>
<tr class="even">
<td align="left">Milvago chimachima</td>
<td align="left">Falconiformes</td>
<td align="left">Falconidae</td>
<td align="left">R</td>
<td align="left">Vertebrados</td>
</tr>
<tr class="odd">
<td align="left">Brotogeris jugularis</td>
<td align="left">Psittaciformes</td>
<td align="left">Psittacidae</td>
<td align="left">R</td>
<td align="left">Frutos</td>
</tr>
<tr class="even">
<td align="left">Eupsittula canicularis</td>
<td align="left">Psittaciformes</td>
<td align="left">Psittacidae</td>
<td align="left">R</td>
<td align="left">Semillas</td>
</tr>
<tr class="odd">
<td align="left">Sublegatus arenarum</td>
<td align="left">Passeriformes</td>
<td align="left">Tyrannidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Myiarchus panamensis</td>
<td align="left">Passeriformes</td>
<td align="left">Tyrannidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="odd">
<td align="left">Pitangus sulphuratus</td>
<td align="left">Passeriformes</td>
<td align="left">Tyrannidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Myiozetetes similis</td>
<td align="left">Passeriformes</td>
<td align="left">Tyrannidae</td>
<td align="left">R</td>
<td align="left">Semillas</td>
</tr>
<tr class="odd">
<td align="left">Icterus pustulatus</td>
<td align="left">Passeriformes</td>
<td align="left">Icteridae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Setophaga petechia</td>
<td align="left">Passeriformes</td>
<td align="left">Parulidae</td>
<td align="left">R.M</td>
<td align="left">Insectos</td>
</tr>
<tr class="odd">
<td align="left">Saltator coerulescens</td>
<td align="left">Passeriformes</td>
<td align="left">Thraupidae</td>
<td align="left">R</td>
<td align="left">Frutos</td>
</tr>
<tr class="even">
<td align="left">Limnodromus griseus</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Moluscos</td>
</tr>
<tr class="odd">
<td align="left">Tringa flavipes</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Hydroprogne caspia</td>
<td align="left">Charadriiformes</td>
<td align="left">Laridae</td>
<td align="left">M</td>
<td align="left">Peces</td>
</tr>
<tr class="odd">
<td align="left">Phalacrocorax brasilianus</td>
<td align="left">Suliformes</td>
<td align="left">Phalacrocoracidae</td>
<td align="left">R</td>
<td align="left">Peces</td>
</tr>
<tr class="even">
<td align="left">Ictinia plumbea</td>
<td align="left">Accipitriformes</td>
<td align="left">Accipitridae</td>
<td align="left">RR.M</td>
<td align="left">Reptiles</td>
</tr>
<tr class="odd">
<td align="left">Falco peregrinus</td>
<td align="left">Falconiformes</td>
<td align="left">Falconidae</td>
<td align="left">M</td>
<td align="left">Aves</td>
</tr>
<tr class="even">
<td align="left">Progne chalybea</td>
<td align="left">Passeriformes</td>
<td align="left">Hirundinidae</td>
<td align="left">R</td>
<td align="left">Insectos</td>
</tr>
<tr class="odd">
<td align="left">Petrochelidon pyrrhonota</td>
<td align="left">Passeriformes</td>
<td align="left">Hirundinidae</td>
<td align="left">M</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Peucaea ruficauda</td>
<td align="left">Passeriformes</td>
<td align="left">Passerellidae</td>
<td align="left">R</td>
<td align="left">Semillas</td>
</tr>
<tr class="odd">
<td align="left">Parkesia noveboracensis</td>
<td align="left">Passeriformes</td>
<td align="left">Parulidae</td>
<td align="left">M</td>
<td align="left">Insectos</td>
</tr>
<tr class="even">
<td align="left">Setophaga petechia</td>
<td align="left">Passeriformes</td>
<td align="left">Parulidae</td>
<td align="left">R.M</td>
<td align="left">Insectos</td>
</tr>
<tr class="odd">
<td align="left">Pluvialis squatarola</td>
<td align="left">Charadriiformes</td>
<td align="left">Charadriidae</td>
<td align="left">M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="even">
<td align="left">Limosa fedoa</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="odd">
<td align="left">Tringa semipalmata</td>
<td align="left">Charadriiformes</td>
<td align="left">Scolopacidae</td>
<td align="left">M</td>
<td align="left">Crustáceos</td>
</tr>
<tr class="even">
<td align="left">Thalasseus maximus</td>
<td align="left">Charadriiformes</td>
<td align="left">Laridae</td>
<td align="left">M</td>
<td align="left">Peces</td>
</tr>
<tr class="odd">
<td align="left">Rynchops niger</td>
<td align="left">Charadriiformes</td>
<td align="left">Laridae</td>
<td align="left">M</td>
<td align="left">Peces</td>
</tr>
<tr class="even">
<td align="left">Falco columbarius</td>
<td align="left">Falconiformes</td>
<td align="left">Falconidae</td>
<td align="left">M</td>
<td align="left">Aves</td>
</tr>
<tr class="odd">
<td align="left">Tyrannus forficatus</td>
<td align="left">Passeriformes</td>
<td align="left">Tyrannidae</td>
<td align="left">M</td>
<td align="left">Insectos</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="analisis-de-diversidad" class="section level2">
<h2>Análisis de diversidad</h2>
<div id="diversidad-verdadera" class="section level3">
<h3>Diversidad Verdadera</h3>
<p align="justify">
La Diversidad verdadera expresa el número equivalente de especies o número de efecto de especies (Hill numbers). Se transforma las comunidades cuyas especies tienen diferntes abundancias, en comunidades con abundancias iguales. Así podemos comparar número de especies entre comunidades.
</p>
<ul>
<li>Resumen de los datos</li>
</ul>
<p align="justify">
Se observaron 76 especies diferentes en todo el paisaje que consistía en tres comunidades de aves: Chomes, Cocorocas y Mata Redonda. En cuanto a la abundancia de individuos, Cocorocas fue el sitio que tuvo más con 1762, seguido por Chomes y Mata Redonda. La cobertura del muestreo fue parecida entre los sitios (Figura 4).
</p>
<pre><code>## Meta-community (class &#39;MetaCommunity&#39;) made of 2546 individuals in 3 
## communities and 76 species. 
## 
## Its sample coverage is 0.99332810483025 
## 
## Community weights are: 
##       Chomes    Cocorocas Mata_redonda 
##    0.3333333    0.3333333    0.3333333 
## Community sample numbers of individuals are: 
##       Chomes    Cocorocas Mata_redonda 
##          401         1762          383 
## Community sample coverages are: 
##       Chomes    Cocorocas Mata_redonda 
##    0.9701369    0.9875187    0.9687229</code></pre>
<p align="center">
<img src="Reporte_gira_files/figure-html/unnamed-chunk-5-1.png" width="672" />
</p>
<p align="center">
<strong>Figura 4</strong>. Gráfico de barras con el número de aves por sitio.
</p>
<p align="justify">
En este estudio se observaron 52 especies en Cocorocas, 34 especies en Chomes y en Mata Redonda 26. La diversidad Beta, el número efectivo de comunidades para este paisaje fue de 2.03, es decir que hay 2 comunidades bien establecidas en el paisaje (Figura 5).
</p>
<pre><code>## HCDT diversity partitioning of order 0 of metaCommunity MC
##  with correction: None
## Alpha diversity of communities: 
##       Chomes    Cocorocas Mata_redonda 
##           34           52           26 
## Total alpha diversity of the communities: 
## [1] 37.33333
## Beta diversity of the communities: 
##     None 
## 2.035714 
## Gamma diversity of the metacommunity: 
## None 
##   76</code></pre>
<p align="center">
<img src="Reporte_gira_files/figure-html/unnamed-chunk-7-1.png" width="672" />
</p>
<p align="center">
<strong>Figura 5</strong>. El rectángulo largo de peso 1 representa la cantidad de especies a nivel de paisaje, igual a 76 especies. El rectángulo estrecho y alto tienen la misma área, el tamaño horizontal muestra la diversidad puntual (37 especies) y el tamaño vertical muestra las comunidades efectivas (2.03).
</p>
</div>
<div id="indice-de-diversidad" class="section level3">
<h3>Índice de diversidad</h3>
<p align="justify">
El q = 1 mide la diversidad , y es equivalente al exponencial del índice de Shannon. Con este índice puedo saber el número de especies <strong>comunes</strong> en la comunidad. Se concentra en la diversidad <strong>local</strong>.
</p>
<pre><code>## HCDT diversity partitioning of order 1 of metaCommunity MC
##  with correction: None
## Alpha diversity of communities: 
##       Chomes    Cocorocas Mata_redonda 
##    12.715533    16.162539     6.218247 
## Total alpha diversity of the communities: 
## [1] 10.85186
## Beta diversity of the communities: 
##     None 
## 2.344227 
## Gamma diversity of the metacommunity: 
##     None 
## 25.43921</code></pre>
<p align="justify">
Podemos observar que Cocorocas tiene una comunidad con más especies comunes (16) que el resto de lugares evaluados (Figura 6).
</p>
<p align="center">
<img src="Reporte_gira_files/figure-html/unnamed-chunk-9-1.png" width="672" />
</p>
<p align="center">
<strong>Figura 6</strong>. El rectángulo largo de peso 1 representa la cantidad de especies comunes a a nivel de paisaje, igual a 25 especies. El tamaño horizontal muestra la cantidad de especies comunes a nivel local (11 especies) y el tamaño vertical muestra las comunidades efectivas (2.34).
</p>
</div>
<div id="indice-de-dominancia" class="section level3">
<h3>Índice de dominancia</h3>
<p align="justify">
El q = 2 mide la dominancia de las especies y es equivalente al Inverso de Simpson. Con este índice puedo saber cuál es el número de especies dominantes en cada comunidad.
</p>
<pre><code>## HCDT diversity partitioning of order 2 of metaCommunity MC
##  with correction: None
## Alpha diversity of communities: 
##       Chomes    Cocorocas Mata_redonda 
##     7.945106    12.371367     3.808818 
## Total alpha diversity of the communities: 
## [1] 6.393261
## Beta diversity of the communities: 
##     None 
## 2.556443 
## Gamma diversity of the metacommunity: 
##   None 
## 16.344</code></pre>
<p align="justify">
En la comunidad de aves Cocorocas hay 12 especies dominantes, es decir que hay más individuos en estas que en las otras especies. A nivel de paisaje, existen 16 especies consideradas como dominantes (Figura 7).
</p>
<p align="center">
<img src="Reporte_gira_files/figure-html/unnamed-chunk-11-1.png" width="672" />
</p>
<p align="center">
<strong>Figura 7</strong>. El rectángulo largo de peso 1 representa la cantidad de especies dominantes a a nivel de paisaje, igual a 16. El tamaño horizontal muestra la cantidad de especies dominantes a nivel local (6.4) y el tamaño vertical muestra las comunidades efectivas (2.55).
</p>
</div>
<div id="perfiles-de-diversidad" class="section level3">
<h3>Perfiles de diversidad</h3>
<p align="justify">
Estos perfiles permiten ver el comportamiento de la diversidad en los diferentes Ordenes. Recordar que el Orden 0 (q= 0) es la riqueza de especies, el Orden 1 (q= 1) son las especies comunes y el orden 2 (q= 2) son las especies dominantes (Figura 8).
</p>
<p align="center">
<img src="Reporte_gira_files/figure-html/unnamed-chunk-12-1.png" width="672" />
</p>
<p align="center">
<strong>Figura 8</strong>.Perfiles de diversidad del Paisaje de Punta Morales.
</p>
<p align="justify">
El índice de diversidad alfa es definida como la diversidad local. En el Orden 0, es decir la riqueza de especies total en el paisaje es 34 especies. El Orden 1 corresponde al total de especies comunes en cada sitio con el supuesto que la cobertura de muestreo fuera la misma (10.85). Por último, el orden 2 es el total de especies dominantes como si la cobertura de muestreo fuera la misma (6.40) (Figura 8 superior izquierda).
</p>
<p align="justify">
También se presenta la diversidad alfa desglosada por comunidades. Así podemos observar que la comunidad de Cocorocas (linea roja) es el que tiene mayor riqueza de especies (52), especies comunes (16) y especies dominantes (12); esto comparado con Chomes (linea negra) y Mata Redonda (línea verde) (Figura 8 arriba derecha).
</p>
<p align="justify">
La diversidad beta es el reemplazo espacial o temporal de las especies. En este paisaje hay de 2 a 2.5 comunidades diferentes (Figura 8 abajo izquierda) <span class="citation">(Marcon et al. 2012)</span>.
</p>
<p align="justify">
El índice de diversidad gamma dice la diversidad total a nivel de paisaje. En el orden 0 se muestra el total de especies en todo el paisaje (76). En el orden 1 se muestra que hay 25 especies a nivel de paisaje que son comunes. Por último el orden 3 muestra que el paisaje tiene 16.34 especies dominantes (Figura 8 abajo derecha).
</p>
</div>
</div>
</div>
<div id="discusion" class="section level1">
<h1>Discusión</h1>
<p align="justify">
El objetivo de la práctica fue observar los hábitats disponibles para aves acuáticas y terrestres en tres sitios del Pacífico Norte de Costa Rica. Cocorocas fue el lugar donde se contabilizó mayor cantidad de especies comunes y dominantes. Lo que pudo darse gracias a que en este sitio el esfuerzo de muestreo fue mayor que en los otros, ya que se pasó mayor tiempo que en Mata Redonda y en las camaroneras. Además en dicho lugar se realizaron observaciones tanto en la mañana como en la tarde, por lo que se cubrió dos horarios pico de avistamiento. Las salineras tienen dos tipos de hábitat diferentes: espejos de agua en las salinas y playa. Esto ofrece recursos diferenciados de alimento y zonas de descanso que las aves pueden utilizar en diferentes momentos del día. Estas características del sitio pudieron facilitar la dominancia de especies como <strong>Himantopus mexicanus</strong> y <strong>Charadrius wilosnia</strong>,que están entre las 12 especies dominantes en Cocorocas. Estas especies utilizan los diques de tierra a lo largo de las salinas como sitios de anidamiento <span class="citation">(Skutch and Stiles 2007)</span>. Ambas especies son residentes, por lo que la importancia de estos sitios de anidamiento es alta para la preservación de estas aves, ya que suelen anidar en colonias dispersas como mecanismo de defensa de depredadores.
</p>
<p align="justify">
Aunque en Mata Redonda no se observaron tantas especies e individuos como en las salinas de Cocorocas o en las camaroneras de Chomes, aves como el galán sin ventura ( <strong><em>Jabiru mycteria</em></strong>) muestran la significancia que tiene este humedal como hábitat de las aves acuáticas. Esto se puede deber a que este Refugio de Vida Silvestre forma parte de una unidad biogeográfica que comprende el Parque Nacional Palo Verde, Humedal Corral de Piedra, los Humedales Las Delicias, La Bolsa y Humedal la Jacinta, por lo que la cercanía de todos estos humedales le asegura al Jabirú alimento y poco gasto energético de traslado <span class="citation">(Ramos 2012)</span>. El <strong>J. mycteria</strong> está catalogado como preocupación menor según la UICN <span class="citation">(Birdlife International 2008)</span>, pero en Costa Rica la población oscila entre los 25 y 83 individuos, lo que es alarmante debido a la baja abundancia y las presiones sufridas por la pérdida de hábitat y cacería <span class="citation">(Villarreal 2009)</span>. Esto convierte al Refugio de Vida Silvestre Mata Redonda en un sitio importante para la conservación de esta especie y las que lo utilizan como descanso y ruta de migración. La baja abundancia de aves en esa zona pudo deberse a la desaparición natural del humedal, lo que las obliga a desplazarse a otros sitios de la zona en busca de alimento <span class="citation">(Pérez-Castillo et al. 2013)</span>.
</p>
<p align="justify">
El hecho de que Cocorocas tuviera la mayor diversidad alfa demuestra que no sólo las áreas protegidas funcionan para conservar la vida silvestre. Este lugar fue el que presentó mayor presión antropogénica, por el mantenimiento de la salina y extracción del producto semanalmente. A pesar de ello, el espejo de agua que ofrece este sitio para descanso y forrajeo es un recurso más que las aves pueden aprovechar, en un mosaico de paisaje donde hay una pérdida de hábitat gracias a procesos de urbanización y cambios de uso del suelo. La inversión para mantener este tipo de actividades donde ofrecen indirectamente servicios ecosistémicos a las aves, puede ser una estrategia interesante para la conservación de aves migratorias y residentes, ayudando a su vez al desarrollo de una actividad económica que ayudaría a los vecinos de las comunidades aledañas.
</p>
<p align="justify">
El índice de diversidad Beta muestra que solamente hay dos comunidades bien establecidas en todo el paisaje, y que la diversidad está representada con 36 especies. Lo anterior pudo darse gracias a que los tres lugares compartían especies entre sí, aunque no en la misma abundancia de individuos. Esto demuestra que hay un reemplazo espacial o temporal de especies, que migran de un sitio a otro influenciado por la disponibilidad del espejo de agua, alimento y horarios de actividad. Fenómenos que son controlados por la subida de la marea <span class="citation">(Torres et al. 2006)</span>.
</p>
<p align="justify">
Las aves acuáticas son residentes comunes de los humedales y espejos de agua estacionales durante determinados meses del año para cubrir necesidades específicas en sus ciclos tales como alimentación, migración, reproducción o sitios de anidamiento <span class="citation">(Blanco and Malvárez 1999)</span>. Lugares sin ningún tipo de acción de conservación sirven de hábitat aves migratorias y residentes. Sin embargo es importante tener también zonas protegidas que aseguren los recursos necesarios para que las aves puedan utilizarlo y no decaigan sus poblaciones. La presencia de especies residente y migratorias en los tres sitios estudiados muestra la importancia de la costa del Pacífico central y norte de nuestro país como hábitat para las aves, y se vuelve vital el promover la conectividad de estos lugares para la conservación de la avifauna silvestre.
</p>
</div>
<div id="bibliografia" class="section level1 unnumbered">
<h1>Bibliografía</h1>
<div id="refs" class="references">
<div id="ref-Resources2016">
<p>Birdlife International (2008) Jabiru mycteria, The IUCN Red List of Threatened Species. 8235:</p>
</div>
<div id="ref-Blanco1999">
<p>Blanco D, Malvárez A (1999) Los humedales como hábitat de aves acuáticas. … Sobre Humedales Subtropicales Y Templados … 2142:</p>
</div>
<div id="ref-Hoffmann2008">
<p>Hoffmann S, Hoffmann A (2008) Is there a “true” diversity? Ecological Economics 65:213–215. doi: <a href="https://doi.org/10.1016/j.ecolecon.2008.01.009">10.1016/j.ecolecon.2008.01.009</a></p>
</div>
<div id="ref-Lou2012">
<p>Lou J, González-Oreja JA (2012) Midiendo la diversidad biológica: más allá del índice de Shannon. Acta Zoologica Lilloana 56:3–14</p>
</div>
<div id="ref-Marcon2012">
<p>Marcon E, Hérault B, Baraloto C, Lang G (2012) The decomposition of Shannon’s entropy and a confidence interval for beta diversity. Oikos 121:516–522. doi: <a href="https://doi.org/10.1111/j.1600-0706.2011.19267.x">10.1111/j.1600-0706.2011.19267.x</a></p>
</div>
<div id="ref-Moreno2011">
<p>Moreno CE, Barragán F, Pineda E, Pavón NP (2011) Reanalyzing alpha diversity: alternatives to understand and compare information about ecological communities. Revista Mexicana de Biodiversidad 82:1249–1261. doi: <a href="https://doi.org/10.1017/CBO9781107415324.004">10.1017/CBO9781107415324.004</a></p>
</div>
<div id="ref-Perez2013">
<p>Pérez-Castillo G, Barboza R, Ramos F (2013) Calidad Del Agua Del Refugio Mata Redonda Y Los. 24:379–392</p>
</div>
<div id="ref-Ramos2012">
<p>Ramos JF (2012) Evaluación de la influencia de la actividad arrocera sobre la calidad del agua que drena hacia el refugio nacional de vida silvestre mata redonda, nicoya, guanacaste, costa rica. 94</p>
</div>
<div id="ref-Stiles2007">
<p>Skutch A, Stiles G (2007) Guía de Aves de Costa Rica, 4th edn. Editoral INBio</p>
</div>
<div id="ref-Torres2006">
<p>Torres M, Quinteros Z, Takano F (2006) Variación temporal de la abundancia y diversidad de aves limícolas en el refugio de vida silvestre Pantanos de Villa, Perú TT - Temporal variation in the abundance and diversity of shorebirds at the Pantanos de Villa Wildlife Refuge, Lima, Peru. Ecología Aplicada 5:119–125</p>
</div>
<div id="ref-Villareal2009">
<p>Villarreal J (2009) en Costa Rica : población y conservación. 22:121–128. doi: <a href="https://doi.org/10.1590/S0103-863X2012000100008">10.1590/S0103-863X2012000100008</a></p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
